export const NOTIFICATION_TYPES = {
  // Work Progress
  WORK_ITEM_UPDATED: 'WORK_ITEM_UPDATED',
  WORK_ITEM_STATUS_CHANGED: 'WORK_ITEM_STATUS_CHANGED',
  // Report Data
  METRICS_UPDATED: 'METRICS_UPDATED',
  KEYWORD_UPDATED: 'KEYWORD_UPDATED',
  AHREFS_METRICS_PROPOSED: 'AHREFS_METRICS_PROPOSED',
  // Admin Actions
  PAYMENT_APPROVED: 'PAYMENT_APPROVED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',
  PAYMENT_UPLOADED: 'PAYMENT_UPLOADED',
  SEO_DEV_ASSIGNED: 'SEO_DEV_ASSIGNED',
  // Custom
  CUSTOM: 'CUSTOM',
} as const

export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES]

export const NOTIFICATION_TYPE_LABELS: Record<NotificationType, string> = {
  WORK_ITEM_UPDATED: 'อัปเดตแผนงาน',
  WORK_ITEM_STATUS_CHANGED: 'เปลี่ยนสถานะแผนงาน',
  METRICS_UPDATED: 'อัปเดต Metrics',
  KEYWORD_UPDATED: 'อัปเดต Keyword',
  AHREFS_METRICS_PROPOSED: 'เสนออัปเดตค่า Ahrefs',
  PAYMENT_APPROVED: 'อนุมัติการชำระเงิน',
  PAYMENT_REJECTED: 'ปฏิเสธการชำระเงิน',
  PAYMENT_UPLOADED: 'อัปโหลดหลักฐานชำระเงิน',
  SEO_DEV_ASSIGNED: 'มอบหมาย SEO Dev',
  CUSTOM: 'การแจ้งเตือนทั่วไป',
}

export const NOTIFICATION_TYPE_GROUPS = {
  แผนงาน: [NOTIFICATION_TYPES.WORK_ITEM_UPDATED, NOTIFICATION_TYPES.WORK_ITEM_STATUS_CHANGED],
  รายงาน: [
    NOTIFICATION_TYPES.METRICS_UPDATED,
    NOTIFICATION_TYPES.KEYWORD_UPDATED,
    NOTIFICATION_TYPES.AHREFS_METRICS_PROPOSED,
  ],
  การชำระเงิน: [
    NOTIFICATION_TYPES.PAYMENT_APPROVED,
    NOTIFICATION_TYPES.PAYMENT_REJECTED,
    NOTIFICATION_TYPES.PAYMENT_UPLOADED,
  ],
  ระบบ: [NOTIFICATION_TYPES.SEO_DEV_ASSIGNED, NOTIFICATION_TYPES.CUSTOM],
} as const
